title: "Kodo Robotics"
description: "コード・ロボティクス — Code for the future of robotics"
url: "https://kodorobotics.com"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache
  - jekyll-feed

markdown: kramdown
permalink: /:categories/:title/
minimal_mistakes_skin: "dark"
logo: "/assets/images/logo.png"
favicon: "/assets/images/favicon.ico"

author:
  name: "Kodo Robotics"

collections:
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: false

footer:
  links:
    - label: "Contact"
      url: "mailto:kodorobotics@gmail.com"